RailsTestApps/siteDraft/config/routes.rb
SiteDraft::Application.routes.draw do
    resources :states

  get "home/index"

   root :to => 'home#index'

end

RailsTestApps/siteDraft/app/models/home.rb
class Home < ActiveRecord::Base
  has_many :states
end

RailsTestApps/siteDraft/app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :home
  attr_accessible :name
end

RailsTestApps/siteDraft/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

RailsTestApps/siteDraft/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @states=State.all
    
  end
end

RailsTestApps/siteDraft/app/controllers/states_controller.rb
class StatesController < ApplicationController
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

RailsTestApps/siteDraft/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsTestApps/siteDraft/app/helpers/home_helper.rb
module HomeHelper
end

RailsTestApps/siteDraft/app/helpers/states_helper.rb
module StatesHelper
end

RailsTestApps/siteDraft/app/views/home/index.html.erb
</head>
<body>
	
	<div class="container" id="container">
		<div class="header" id="header">
			<h1>ProFinder</h1>
		</div>
		<div class="boxcontainer" id="options">
			<div class="box" id="states container">
				<p class="label"> State </p>
				<div class="category" id="box0div">
					
					<ul id="box0">
							<% @States.each do |state| %>
						      <li><%= state.name %></li>
						    <% end %>
					</ul>
						
				</div>
			</div>
			<div class="box" id="cities container">
				<p class="label"> City </p>
				<div class="category" id="box1div">
					
					<ul id="box1">
					</ul>
					
				</div>
			</div>
			<div class="box" id="Category Container">
				<p class="label"> Category </p>
				<div class="category" id="box3div">
					<ul id="box3">
					</ul>
				</div>
			</div>
			<div class="box" id="Skills Container">
				<p class="label"> Skills </p>
				<div class="category" id="box4div">
					<ul id="box4">
					</ul>
				</div>
			</div>
		</div>
				
		<div id="Results" style="clear:both;text-align:center;">
				<p> Search Results </p>
				<p> result </p>
				
				
		</div>


		</div>
	</div>

RailsTestApps/siteDraft/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SiteDraft</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

RailsTestApps/siteDraft/app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsTestApps/siteDraft/app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

RailsTestApps/siteDraft/app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= state.name %></td>
    <td><%= link_to 'Show', state %></td>
    <td><%= link_to 'Edit', edit_state_path(state) %></td>
    <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New State', new_state_path %>

RailsTestApps/siteDraft/app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

RailsTestApps/siteDraft/app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @state.name %>
</p>


<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>